### ISSUE TITLE
投稿した際に、Twitter と紐付けて Twitter で共有する事ができないか？

### ISSUE THREAD

**Issue by taiseiyo** [yamatoken/qiita_org#11]
Qiita にはTwitter と紐付けて Twitter で共有するという機能が存在しているので
それを qiita_org 上でも実装して欲しい。

**Comment by yamatoken** [comment]
提案ありがとうございます．実装させていただきました．
version0.1.25からQiitaの方でTwitterと連携しているときに，公開投稿をするとTweetされるようになってます．
この機能を追加するにあたり，template.orgに#+Twitterという文を追加しています．
この後ろをOnまたはOffとすることでTweetするかを決めることができます．
OnになっていてもTeamsや限定共有投稿ではTweetされない仕様です．

ぜひバージョンを上げて試して見てください．何か不具合等ありましたら，お手数おかけしますが連絡お願いします．

**Comment by taiseiyo** [comment]
実装お疲れ様でした。
こちらで確認を確認をさせて頂きます。

バグなどを発見したら新しい Issues を作成させて頂きます。
