### ISSUE TITLE
qiita all を行う際に、template.org を除くようにして post 欲しい

### ISSUE THREAD

**Issue by taiseiyo** [yamatoken/qiita_org#13]
org ファイルをまとめて同じディレクトリに置いているので、qiita all を行う際に、template.org も post してしまうので qiita all を行う際には template.org を除外して欲しいです。

**Comment by yamatoken** [comment]
ご提案ありがとうございます．allコマンドに関してはtemplate.orgを投稿しないように変更いたしました．もしtemplate.orgを投稿したければpostコマンドを使えば投稿できるようにしています．

バージョンを上げてallコマンドを試して見てください．
またバグ等何かございましたらIsuueをいただけると幸いです．
よろしくお願いします．

**Comment by syasin-5d** [comment]
特定のファイルを無視するのは直感に反するというか、あまりイケていないように思います。
`qiita all --exclude template.org` のように引数で除外させるか、
.gitignore のように外部ファイルで除外ファイルを定義できると良い感じな気がします。

**Comment by yamatoken** [comment]
ご意見ありがとうございます．
確かにallというコマンドの名前からして，初めから特定のファイルを除外しているのは不自然ですね．
ご提案いただいたように'--exclude'のオプションをつけることで引数から除外できるようにして見たいと思います．

**Comment by taiseiyo** [comment]
@syasin-5d 
なるほど。それはその通りだと思います。

@yamatoken 
アップデートされたらコメントお願いします。

**Comment by yamatoken** [comment]
@taiseiyo @syasin-5d
allを実行するときに`--exclude [files]`をつけることでfilesに該当するものを除外するようにしました．
version0.1.30にて反映されているので確認して見てください．

バグ等の報告をしてくださるとありがたいです．

**Comment by yamatoken** [comment]
@taiseiyo @syasin-5d
allを実行するときに`--exclude files`をつけることでfilesに該当するものを除外するようにしました．
version0.1.30にて反映されているので確認して見てください．

バグ等の報告をしてくださるとありがたいです．
