### ISSUE TITLE
動きません

### ISSUE THREAD

**Issue by minamiguchihiro** [yamatoken/qiita_org#17]
いつも使わせて頂いています. 0.1.32に上げたらエラーが出ました.よろしくお願いします.
``` bash
$ qiita post README.org
Traceback (most recent call last):
	7: from /usr/local/bin/qiita:23:in `<main>'
	6: from /usr/local/bin/qiita:23:in `load'
	5: from /var/lib/gems/2.5.0/gems/qiita_org-0.1.32/exe/qiita:3:in `<top (required)>'
	4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	2: from /var/lib/gems/2.5.0/gems/qiita_org-0.1.32/lib/qiita_org.rb:13:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': /var/lib/gems/2.5.0/gems/qiita_org-0.1.32/lib/qiita_org/upload.rb:101: void value expression (SyntaxError)
..., file_name))? @file_url : next
...                               ^
```

**Comment by minamiguchihiro** [comment]
rubyのバージョンを2.7.1に上げました. その後も, 同じエラーが出ました. よろしくお願いします.

**Comment by yamatoken** [comment]
報告ありがとうございます。
お手数おかけしますが、
・ubuntuのバージョン
・’ruby -v‘でrubyのバージョンが変わっているか
・エラー文が最初と変わっていないか
を確認していただきたいです。
よろしくお願いします。

**Comment by daddygongon** [comment]
file_name))? @file_url : next
の　?の前にspace入れてみてください．関係ないとは思うけど．．．

あと，nextはcへのconvertで引っかかりそうなので，if ~ else ~ endで書き直してみてもらえますか．それで行けるならそうしましょう．そうなってくるとnextが通る方が文法の間違いかもしれないので．．．

**Comment by daddygongon** [comment]
settingで私のところへもissu, pull requestにactionがあった時，defaultでmailが投げられるように変更してくださいますか？

**Comment by yamatoken** [comment]
if elseにしてバージョンを上げました．
@minamiguchihiro 
qiita_orgのバージョンを上げてもう一度試して見てください．よろしくお願いします．

@daddygongon
リポジトリに招待しました．

**Comment by minamiguchihiro** [comment]
qiita_orgのバージョンを上げるとqiita post 出来るようになりました.
ありがとうございました.

**Comment by daddygongon** [comment]
最新版で

**Comment by daddygongon** [comment]
最新版0.1.33でこの不具合は修正しました．0.1.33がreleaseされてないようですね．よろしく．
