### ISSUE TITLE
新しい記事がpostできません

### ISSUE THREAD

**Issue by YOU-GO9** [yamatoken/qiita_org#19]
いつも使わせて頂いてます。
新たに作成した記事をpostしようとすると以下のエラーが出ました。
すでにpostしたことのある記事は問題なくpostできます。
emacsのバージョンは25.2.2です。
qiita_orgのバージョンは0.1.33です。
よろしくお願いします。

```bash
$ qiita post leap_year.org public
["in qiita_org.rb", ["leap_year.org", "public"]]
"leap_year.org"
"public"
[{:name=>"tag1"}, {:name=>"tag2"}]
config file path: /home/yugo
Can not make leap_year.md
Please confirm emacs version.
```

**Comment by djj31370** [comment]
私も同じエラーが出てます。


``` bash
$ qiita post c7_roman_numerals.org
["in qiita_org.rb", ["c7_roman_numerals.org"]]
"c7_roman_numerals.org"
"private"
[{:name=>"ruby"}, {:name=>"roman"}]
config file path: /home/masaki
Can not make c7_roman_numerals.md
Please confirm emacs version.
```

**Comment by yamatoken** [comment]
ご報告ありがとうございます．

qiita_orgで使用しているorgをmdにexportするパッケージの問題で，emacsのバージョンは26以上を推奨しています．emacsのバージョンを上げて見てください．

また，orgの文法が間違っている場合もmdに変換できずこのようなエラーが出ます．
一度emacsでファイルを開き，ctrl+c, ctrl+e, h, o と入力してください．文法が間違っている場合はエラーが出ます．例えば，includeしているファイルが無いなどです．
お手数おかけしますが，上記の対応をして見てください．そのご報告をお願いします．

エラー文がわかりづらくなってしまっているので，改善したいと思います．

**Comment by YOU-GO9** [comment]
確認したところorg内のincludeしているファイルの名前をタイプミスしていました。

お手数をおかけしました

**Comment by daddygongon** [comment]
このエラーは，
Can not convert org doc to markdown.
Check the org doc description converting in emacs by 'ctrl+c, ctrl+e, h, o',
or emacs version above 26.
とでもしましょう．
