### ISSUE TITLE
Is the vendor data needed?

### ISSUE THREAD

**Issue by mensfeld** [yamatoken/qiita_org#20]
While reviewing the changes for this lib, I noticed, that the vendor/ge,s directory is being included.

Is this needed? Usually, it's added by mistake and causes:
a) confusion
b) problems when tracking changes
c) makes gem much bigger than it could be

ref: https://github.com/yamatoken/qiita_org/tree/master/gems/ruby/2.7.0

If the presence of vendor data is valid I would love the reasoning. Thanks!

**Comment by yamatoken** [comment]
The directories which you pointed out are unintentionally left in the gem.
We really agree with your opinion or suggestions on the vendor/gems issue.
The related directories are deleted in the current version.
Thank you for noticing the mistake.

**Comment by yamatoken** [comment]
The directories which you pointed out are unintentionally left in the gem.
We really agree with your opinion or suggestions on the vendor/gems issue.
The related directories are deleted in the current version.
Thank you for noticing the mistake.

**Comment by mensfeld** [comment]
Thank you for taking action :) have a great end of the year! I'm closing this issue now. Going to re-open if I find anything again.
